version: '3.7'

services:

  couriers-api:
    image: "${APP_API_IMAGE_NAME}"
    environment:
      - DB_USERNAME=${APP_DB_USERNAME}
      - DB_PASSWORD=${APP_DB_PASSWORD}
      - DB_DATABASE=${APP_DB_NAME}
      - DB_PORT=${APP_DB_PORT}
      - DB_HOST=${APP_DB_HOST}
    ports:
      - "8008:8008"
    depends_on:
      -  couriers-db

networks:
  default:
    name: ${APP_NETWORK}
    external: true
